# Generated by Django 3.2.9 on 2021-12-01 19:55

from django.db import migrations, models
import django.db.models.deletion
import person_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=person_manager.models.person_image_path_handler)),
                ('personnel_number', models.CharField(max_length=30)),
                ('vk_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='VK Username')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
            options={
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_manager.person')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=6)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person_manager.person')),
            ],
        ),
    ]
